name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-13
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: yarn install
      - name: Run lint
        run: yarn lint
